### ISSUE TITLE
Some IDs fail to render

### ISSUE THREAD

**Issue by sama9767** [bgcarlisle/cthist#17]
Hi @bgcarlisle😄,
Thanks for this awesome package. Since the recent update, some IDs fail to render. Can you help? Thanks!

```
# example id that fails to render (other similar ids: "NCT00163267", "NCT00274651")
cthist::clinicaltrials_gov_download("NCT00098137")
#> Error downloading version: NCT00098137 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(pcdate) == 10) {: argument is of length zero
#>
 #> Trying again ...
#> Error downloading version: NCT00098137 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(pcdate) == 10) {: argument is of length zero
#> 
#> Trying again ...
#> Error downloading version: NCT00098137 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(pcdate) == 10) {: argument is of length zero
```

**Comment by bgcarlisle** [comment]
This bug has been fixed https://github.com/bgcarlisle/cthist/commit/df1991468a7c1b6a07d14f008497fbaffa20ae07

The fix will be incorporated into the next update that I send to CRAN (will be a few days)

In the meantime, re-install `cthist` using the instructions for the development version here:

https://github.com/bgcarlisle/cthist/blob/main/README.md

**Comment by bgcarlisle** [comment]
I just submitted the updates of the package to CRAN and got the following response:

> CRAN submissions will be offline from Jul 21, 2023 to Aug 7, 2023 (CRAN team vacation and maintenance work).
> --
> During this time, the submission of packages is not possible.
> Sorry for any inconvenience.

If you need these data downloaded before then, you'll have to install the dev version via `install_github()`

**Comment by sama9767** [comment]
Thank you so much for this. I am still facing the issue with other ids (the
ones I posted on github works now). Please see my following reprex for
reference.

``` r
library(cthist)
library(dplyr)
# reading Intovalue raw data
intovalue_raw <- rio::import("
https://github.com/maia-sh/intovalue-data/blob/main/data/processed/trials.rds?raw=true
")

# get intovalue test data-set
intovalue_test <- intovalue_raw %>% filter(registry ==
"ClinicalTrials.gov") %>% slice(1:10)

# getting trial history record for intovalue test dataset
clinicaltrials_gov_download(intovalue_test$id, "version.csv" )
#> NCT00742495 - 1 of 7
#> NCT00742495 - 2 of 7
#> NCT00742495 - 3 of 7
#> NCT00742495 - 4 of 7
#> NCT00742495 - 5 of 7
#> NCT00742495 - 6 of 7
#> NCT00742495 - 7 of 7
#> 2023-07-27 12:02:24 NCT00742495 processed (7 versions, 10%)
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Trying again ...
#> Error downloading version: NCT00003636 version 0
#> Here's the original error message:
#> Error in if (stringr::str_length(startdate) == 10) {: argument is of
length zero
#>
#> Recovered from error successfully
#> Error in versiondata$ostatus: $ operator is invalid for atomic vectors
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org
)</sup>

Sincerely,
Sam

**Comment by bgcarlisle** [comment]
Thanks for the note!

This bug has been fixed:

https://github.com/bgcarlisle/cthist/commit/5d678a7db1ee0aa646822f85e4b08e0e02cf11b9

Let me know if you notice anything else!
